##################################################
##  configuration file.                     ##
## Use this file to customize your  analysis ##
##################################################

SE_SUFFIX: ".fastq"
R1_SUFFIX: "_R1.fastq"
#R2_SUFFIX: "_R2.fastq.bz2"
BOWTIE2_INDEX_PATH: "/storage/zhangyanxiaoLab/share/bowtie2_index/"
